version: '2'

services:

  mysql:
    build:
      context: ./docker/mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=LMM_ROOT_USER_PASSWORD
      - MYSQL_DATABASE=deneva_cuatro
      - MYSQL_USER=LMM_DB_USER
      - MYSQL_PASSWORD=LMM_USER_PASSWORD

  eventstore:
    image:
      eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"